image_size: 256  #
num_channels: 256  
num_res_blocks: 2  
channel_mult: "1,2,4"  #
learn_sigma: True  
class_cond: False  
use_checkpoint: False 
attention_resolutions: "16,8,4" 
num_heads: 4
num_head_channels: 64 
num_heads_upsample: -1  
use_scale_shift_norm: True  
dropout: 0.1  
resblock_updown: True  
use_fp16: False  
use_new_attention_order: False 
model_path: models/diffusion_ffhq_256_epoch50.pt


